"""
Django settings for opencook project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0_!nh-wta@p2#k=dm6lmohono8xklb6ltdrl_p4cxfb!wcxyju'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mainapp',
    'recipe',
]     # 單元30 要安裝 session, 去做 python 的 migration, 不過在之前系統已經預設安裝, 在過去 migration 的時候. 事實上已經 migrate 過了, 也就是說資料庫可以存取到 session 的資料

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]   # 單元30 要安裝 session, 去做 python 的 migration, 不過在之前系統已經預設安裝, 在過去 migration 的時候. 事實上已經 migrate 過了, 也就是說資料庫可以存取到 session 的資料

ROOT_URLCONF = 'opencook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\','/')],
        # DIR, default setting [], 指資料夾的位子是什麼, 意思是把 templates 檔案位子抓出來, 用絕對位子去做處理, 轉成 replace('\\','/')
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opencook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# 設定資料庫 SQLite 3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',      #ENGINE 使用的資料庫引擎, 可以設定 MySQL, SQLite 或是 pgSQL
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # os.path.join(BASE_DIR, 使用系統目前所在的資料夾
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
# 單元29 放資料夾的地方
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')   # 指定 static 這個資料夾可以吃我們放置靜態檔案的位子
]
